name: Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: 46.17.172.232
          username: u693572706
          port: 65002
          key: AUIDNACKat5m66VIqYLUevBw7WKahGoW9aRDqDa6b3I
          script: "cd /domains/autopartscjce.com && deploy.sh" 