on: push
name: Publish Website
jobs:
  web-deploy:
    name: 🚀 Deploy Website Every Commit
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get Latest Code
      uses: actions/checkout@v3
    
    - name: 📂 Sync Files
      uses: SamKirkland/web-deploy@v1
      with:
        target-server: autopartscjce.com
        remote-user: u693572706 
        private-ssh-key: AUIDNACKat5m66VIqYLUevBw7WKahGoW9aRDqDa6b3I
        destination-path: ~/domains/autopartscjce.com/